---
version: 2.1

orbs:
  op: twdps/onepassword@1.0.0

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2

  development:
    jobs:
      - create-system:
          name: Create Development Styra System
          context: << pipeline.parameters.context >>
          environment: dev
          branch: dev
          filters: *on-push-main

jobs:
  create-system:
    parameters:
      environment:
        type: string
        description: Environment to configure
      branch:
        type: string
        description: branch to track policies on
    docker:
      - image: docker.io/twdps/circleci-python-builder:stable
    shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - op/install-op:
          os: Alpine
      - run:
          name: Ensure API Token is set
          command: |
            if [ ! ${STYRA_API_TOKEN} ]; then
              echo "Styra token is not being set"
              exit 1
            fi
      - run:
          name: Configure system
          command: |
            pipenv install
            pipenv run python ./configure-system.py << parameters.environment >> << parameters.branch >>
      - run:
          name: Sync Branch
          command: |
            git branch -f << parameters.branch >> $CIRCLE_SHA1
            git push https://$GITHUB_ACCESS_TOKEN@github.com/ThoughtWorks-DPS/teams-authorization-policies.git << parameters.branch >>
