---
version: 2.1

orbs:
  op: twdps/onepassword@1.1.0

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2

  development:
    jobs:
      - test-rego:
          name: Test and Lint policies
          filters: *on-push-main
      - create-system:
          name: Create/Update Development Styra System
          context: << pipeline.parameters.context >>
          environment: dev
          branch: dev
          requires:
            - Test and Lint policies
      - deploy-slp:
          name: Deploy SLP to dev
          context: << pipeline.parameters.context >>
          environment: dev
          cluster: prod-us-east-1
          requires:
            - Create/Update Development Styra System

  release:
    jobs:
      - create-system:
          name: Create/Update QA Styra System
          context: << pipeline.parameters.context >>
          environment: qa
          branch: qa
          filters: *on-tag-main
      - deploy-slp:
          name: Deploy SLP to qa
          context: << pipeline.parameters.context >>
          environment: qa
          cluster: prod-us-east-1
          requires:
            - Create/Update QA Styra System
          filters: *on-tag-main
      - approve-prod:
          name: Approve Deployment to Production
          type: approval
          requires:
            - Create/Update QA Styra System
          filters: *on-tag-main
      - create-system:
          name: Create/Update Production Styra System
          context: << pipeline.parameters.context >>
          environment: prod
          branch: prod
          requires:
            - Approve Deployment to Production
          filters: *on-tag-main
      - deploy-slp:
          name: Deploy SLP to prod
          context: << pipeline.parameters.context >>
          environment: prod
          cluster: prod-us-east-1
          requires:
            - Create/Update Production Styra System
          filters: *on-tag-main

jobs:
  deploy-slp:
    parameters:
      environment:
        type: string
        description: Environment to configure
      cluster:
        type: string
        description: cluster to deploy to
    docker:
      - image: docker.io/twdps/circleci-python-builder:stable
    shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - op/install-op:
          os: Alpine
          shell: /bin/bash -eo pipefail
      - run:
          name: Generate namespace config
          command: |
            pipenv install
            pipenv run python configure_k8s_namespace.py << parameters.environment >>
      - run:
          name: Install kubectl
          command: |
            curl -SLO "https://storage.googleapis.com/kubernetes-release/release/v1.24.3/bin/linux/amd64/kubectl"
            sudo chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: pull kubeconfig
          command: |
            mkdir -p ~/.kube
            ENV=<< parameters.cluster >> op inject -i kubeconfig.tpl -o ~/.kube/config
      - run:
          name: Setup OPA in Namespace
          command: |
            kubectl apply -f envoyfilter.yaml --namespace twdps-core-labs-team-<< parameters.environment >>
            kubectl apply -f opaconfig.yaml --namespace twdps-core-labs-team-<< parameters.environment >>
            kubectl apply -f slp.yaml --namespace twdps-core-labs-team-<< parameters.environment >>

  test-rego:
    docker:
      - image: docker.io/twdps/circleci-base-image:alpine-stable
    steps:
      - checkout
      - run:
          name: Install opa cli
          command: |
            curl -L -o opa https://openpolicyagent.org/downloads/v0.44.0/opa_linux_amd64_static
            chmod 755 ./opa
            sudo mv ./opa /usr/local/bin/opa
            opa version
      - run: opa fmt --diff --fail policy/
      - run: opa check policy/
      - run: opa test -v policy/
  create-system:
    parameters:
      environment:
        type: string
        description: Environment to configure
      branch:
        type: string
        description: branch to track policies on
    docker:
      - image: docker.io/twdps/circleci-python-builder:stable
    shell: << pipeline.parameters.shell-options >>
    steps:
      - checkout
      - op/install-op:
          os: Alpine
          shell: /bin/bash -eo pipefail
      - run:
          name: Ensure API Token is set
          command: |
            if [ ! ${STYRA_API_TOKEN} ]; then
              echo "Styra token is not being set"
              exit 1
            fi
      - run:
          name: Sync Branch
          command: |
            git branch -f << parameters.branch >> $CIRCLE_SHA1
            git push https://$GITHUB_ACCESS_TOKEN@github.com/ThoughtWorks-DPS/teams-authorization-policies.git << parameters.branch >>
      - run:
          name: Configure system
          command: |
            pipenv install
            pipenv run python configure_system.py << parameters.environment >> << parameters.branch >>
